### ISSUE TITLE
IPNetwork.TryParse throws an exception when provided with "*" 

### ISSUE THREAD

**Issue by louisledev** [lduchosal/ipnetwork#296] opened 2023-12-20 16:59 UTC
By convention, TryXXX method don't throw but rather returns `false` when failing.
However, when  calling
```
IPNetwork.TryParse("*", out var network);   
```
we get the following exception:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.IPNetwork.InternalParse(Boolean tryParse, String network, ICidrGuess cidrGuess, Boolean sanitanize, IPNetwork& ipnetwork)
   at System.Net.IPNetwork.TryParse(String network, IPNetwork& ipnetwork)
```

tested with version 2.6.618

**Comment by lduchosal** [comment] 2024-01-17 22:01
PR Welcome

**Comment by lduchosal** [comment] 2024-01-18 07:30
Cannot reproduce, TestUnit added Test_IPNetwork_TryParse_Issue294 succeed, closing this issue

**Comment by lduchosal** [comment] 2024-01-18 07:31
Cannot reproduce, TestUnit added Test_IPNetwork_TryParse_Issue294 succeed, closing this issue

**Closed by lduchosal** 2024-01-18 07:30 UTC
Labels: bug, help wanted, will fix
